// Auto-generated for chat template - DO NOT EDIT
// Generated by create-app-direct.js
// Chain ID: 11155931 (RISE Testnet)

// Import ABIs
import ChatAppABI from './abi/ChatApp.json';

export const contracts = {
  ChatApp: {
    address: '0xcf7b7f03188f3b248d6a3d4bd589dc7c31b55084' as const,
    deploymentTxHash: '0xaa54b83133294bcdabb7ef2f12e2728494a2c4a005cf78948fa14ffbe2181033',
    blockNumber: 15131606,
    abi: ChatAppABI
  }
} as const;

// Type exports
export type ContractName = keyof typeof contracts;
export type Contracts = typeof contracts;

// Helper functions
export function getContract<T extends ContractName>(name: T): Contracts[T] {
  return contracts[name];
}

export function getContractAddress(name: ContractName): string {
  return contracts[name].address;
}

export function getContractABI(name: ContractName) {
  return contracts[name].abi;
}

// Re-export specific contract for convenience
export const CHATAPP_ADDRESS = '0xcf7b7f03188f3b248d6a3d4bd589dc7c31b55084' as const;
export const CHATAPP_ABI = ChatAppABI;
