// Auto-generated for chat template - DO NOT EDIT
// Generated by create-app-direct.js
// Chain ID: 11155931 (RISE Testnet)

// Import ABIs
import WordleABI from "./abi/SimpleWordle.json";

export const contracts = {
    SimpleWordle: {
        address: "0xdec7539a3a95c343bd0c4c8559da424fa23956a4" as const,
        deploymentTxHash:
            "0x27ae3d1093d20f74665e231c3998cea71f29466580ef0717334a81ebe20da3fd",
        blockNumber: 11155931,
        abi: WordleABI,
    },
} as const;

// Type exports
export type ContractName = keyof typeof contracts;
export type Contracts = typeof contracts;

// Helper functions
export function getContract<T extends ContractName>(name: T): Contracts[T] {
    return contracts[name];
}

export function getContractAddress(name: ContractName): string {
    return contracts[name].address;
}

export function getContractABI(name: ContractName) {
    return contracts[name].abi;
}

// Re-export specific contract for convenience
export const WORDLE_ADDRESS =
    "0xdec7539a3a95c343bd0c4c8559da424fa23956a4" as const;
export const WORDLE_ABI = WordleABI;
